# Generated by Django 3.2.7 on 2021-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
