# Generated by Django 3.2.7 on 2021-10-09 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_enroll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='classroom.classroom'),
        ),
    ]
